version: "3.9"

networks:
  frontend-net:
  backend-net:

volumes:
  db-data:

services:
  frontend:
    image: nginx:alpine
    container_name: frontend
    ports:
      - "8080:80" # 端口映射， 将宿主机的 8080 端口映射到容器的 80 端口，容器的 nginx 服务可以通过宿主机的 8080 端口访问
    volumes: # 挂载配置文件和静态文件， 方便本地开发调试， 修改后无需重建镜像， 直接重启容器即可生效， 提高开发效率， 但生产环境建议使用dockerfile构建镜像， 避免依赖宿主机文件系统
      - ./frontend/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/index.html:/usr/share/nginx/html/index.html
    networks: # 连接到前端网络， 方便与 backend 通信
      - frontend-net
    depends_on: # 确保 backend 在 frontend 之前启动
      - backend

  backend:
    build: ./backend # 构建 backend 镜像， Dockerfile 位于 ./backend 目录下
    container_name: backend # 自定义容器名称
    expose:
      - "3000" # 仅向链接的服务暴露端口， 不映射到宿主机
    env_file:
      - ./env/prod.env
    networks:
      - frontend-net
      - backend-net
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: secret
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend-net
    # ❌ 没有 ports， 数据库不暴露在宿主机上， 只能被 backend 访问， 提高安全性
